import React, { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { RouteProp, useRoute } from '@react-navigation/native';
import { PrimaryButton } from '../components/PrimaryButton';
import { ScreenContainer } from '../components/ScreenContainer';
import { useRootNavigation } from '../hooks/useRootNavigation';
import { logEvent } from '../services/analyticsService';
import { mapAuthError, requestPasswordReset, signIn, signUp } from '../services/authService';
import { linkCampaignToCurrentUser } from '../services/campaignService';
import { clearPendingSignupOtp } from '../services/pendingOtp';
import { hasReferralCodeInUrl } from '../services/referralService';
import { colors, radius, spacing, typography } from '../theme/colors';
import { RootStackParamList } from '../types';
type Mode='signIn'|'signUp'|'forgotPassword'; type AuthRouteProp=RouteProp<RootStackParamList,'Auth'>; const RESET_COOLDOWN_MS=30000;
export default function AuthScreen(){
 const navigation=useRootNavigation(); const{params}=useRoute<AuthRouteProp>(); const canGoBack=navigation.canGoBack(); const isAuraAcquisition=params?.context==='measure_aura';
 const[mode,setMode]=useState<Mode>(()=>params?.initialMode??(hasReferralCodeInUrl()?'signUp':'signIn')); const[email,setEmail]=useState(''); const[password,setPassword]=useState(''); const[showPassword,setShowPassword]=useState(false); const[loading,setLoading]=useState(false); const[error,setError]=useState<string|null>(null); const[successMessage,setSuccessMessage]=useState<string|null>(null); const[showAlreadyRegistered,setShowAlreadyRegistered]=useState(false); const[showLoginRecoveryHint,setShowLoginRecoveryHint]=useState(false); const[resetCooldownActive,setResetCooldownActive]=useState(false);
 useEffect(()=>{if(mode==='signUp')void logEvent('signup_viewed',{context:params?.context??null});},[mode,params?.context]);
 useEffect(()=>{void clearPendingSignupOtp();},[]);
 function resetTransientState(){setError(null);setSuccessMessage(null);setShowAlreadyRegistered(false);setShowLoginRecoveryHint(false);} function switchMode(next:Mode){resetTransientState();setPassword('');setMode(next);}
 async function handleSubmit(){resetTransientState();setLoading(true);try{if(mode==='signIn'){await signIn(email.trim(),password);await linkCampaignToCurrentUser();await clearPendingSignupOtp();await logEvent('login',{context:params?.context??null});}else{if(password.length<8){setError('Usa una contraseña de al menos 8 caracteres.');return;}void logEvent('signup_started',{context:params?.context??null});const{status,userId}=await signUp(email.trim(),password);if(status==='alreadyRegistered'){setShowAlreadyRegistered(true);}else if(status==='signedIn'){await linkCampaignToCurrentUser();await clearPendingSignupOtp();await logEvent('signup_completed',{context:params?.context??null},userId);}else{setError('No pudimos iniciar tu sesión. Intenta de nuevo.');}}}catch(e){const message=mapAuthError(e);setError(message);if(mode==='signIn'&&message==='Correo o contraseña incorrectos.')setShowLoginRecoveryHint(true);}finally{setLoading(false);}}
 async function handleRequestReset(){if(resetCooldownActive)return;resetTransientState();setLoading(true);try{await requestPasswordReset(email.trim());setSuccessMessage('Si el correo existe, te enviamos un enlace para recuperar tu contraseña.');setResetCooldownActive(true);setTimeout(()=>setResetCooldownActive(false),RESET_COOLDOWN_MS);}catch(e){setError(mapAuthError(e));}finally{setLoading(false);}}
 if(showAlreadyRegistered)return <ScreenContainer style={styles.container} onBack={canGoBack?()=>navigation.goBack():undefined}><View style={styles.header}><Text style={styles.wordmark}>AURA VS</Text><Text style={styles.successText}>Esta cuenta ya existe.</Text></View><View style={styles.actions}><PrimaryButton label="INICIAR SESIÓN" onPress={()=>switchMode('signIn')}/><PrimaryButton variant="text" label="RECUPERAR CONTRASEÑA" onPress={()=>switchMode('forgotPassword')}/></View></ScreenContainer>;
 if(successMessage)return <ScreenContainer style={styles.container} onBack={canGoBack?()=>navigation.goBack():undefined}><View style={styles.header}><Text style={styles.wordmark}>AURA VS</Text><Text style={styles.successText}>{successMessage}</Text></View><PrimaryButton label="VOLVER" onPress={()=>switchMode('signIn')}/></ScreenContainer>;
 if(mode==='forgotPassword')return <ScreenContainer style={styles.container} onBack={canGoBack?()=>navigation.goBack():undefined}><View style={styles.header}><Text style={styles.wordmark}>AURA VS</Text><Text style={styles.subtitle}>Te mandamos un link para elegir una contraseña nueva.</Text></View><View style={styles.form}><TextInput style={styles.input} placeholder="Email" placeholderTextColor={colors.textMuted} autoCapitalize="none" autoCorrect={false} keyboardType="email-address" value={email} onChangeText={setEmail}/>{error&&<Text style={styles.error}>{error}</Text>}</View><View style={styles.actions}><PrimaryButton label={loading?'ENVIANDO...':resetCooldownActive?'YA LO ENVIAMOS -- ESPERA UN MOMENTO':'ENVIAR ENLACE'} disabled={loading||!email||resetCooldownActive} onPress={handleRequestReset}/><PrimaryButton variant="text" label="Volver a iniciar sesión" onPress={()=>switchMode('signIn')}/></View></ScreenContainer>;
 return <ScreenContainer style={styles.container} onBack={canGoBack?()=>navigation.goBack():undefined}><View style={styles.header}><Text style={styles.wordmark}>AURA VS</Text><Text style={styles.subtitle}>{mode==='signIn'?'Entra a tu cuenta.':isAuraAcquisition?'Crea tu cuenta gratis para guardar tu resultado.':'Crea tu cuenta.'}</Text>{mode==='signUp'&&isAuraAcquisition&&<Text style={styles.microcopy}>Solo email + contraseña · después vas directo al Scan</Text>}</View><View style={styles.form}><TextInput style={styles.input} placeholder="Tu email" placeholderTextColor={colors.textMuted} autoCapitalize="none" autoCorrect={false} keyboardType="email-address" value={email} onChangeText={setEmail}/><View style={styles.passwordRow}><TextInput style={styles.passwordInput} placeholder="Contraseña (8+ caracteres)" placeholderTextColor={colors.textMuted} secureTextEntry={!showPassword} autoCapitalize="none" autoCorrect={false} spellCheck={false} value={password} onChangeText={setPassword}/><Pressable onPress={()=>setShowPassword(v=>!v)} hitSlop={10} style={styles.toggle}><Text style={styles.toggleText}>{showPassword?'OCULTAR':'MOSTRAR'}</Text></Pressable></View>{mode==='signIn'&&<Pressable onPress={()=>switchMode('forgotPassword')} hitSlop={6}><Text style={styles.forgotLink}>¿Olvidaste tu contraseña?</Text></Pressable>}{error&&<Text style={styles.error}>{error}</Text>}{showLoginRecoveryHint&&<PrimaryButton variant="ghost" label="RECUPERAR CONTRASEÑA" onPress={()=>switchMode('forgotPassword')}/>}</View><View style={styles.actions}><PrimaryButton label={loading?'...':mode==='signIn'?'ENTRAR':isAuraAcquisition?'⚡ CONTINUAR Y MEDIR MI AURA':'CREAR CUENTA'} disabled={loading||!email||!password} onPress={handleSubmit}/><PrimaryButton variant="text" label={mode==='signIn'?'¿No tienes cuenta? Regístrate':'¿Ya tienes cuenta? Entra'} onPress={()=>switchMode(mode==='signIn'?'signUp':'signIn')}/></View></ScreenContainer>;
}
const styles=StyleSheet.create({container:{justifyContent:'center'},header:{marginBottom:spacing.xl,alignItems:'center'},wordmark:{...typography.hero,color:colors.textPrimary,letterSpacing:1},subtitle:{...typography.body,color:colors.textSecondary,marginTop:spacing.xs,textAlign:'center'},microcopy:{...typography.caption,color:colors.accent,marginTop:spacing.sm,textAlign:'center'},successText:{...typography.body,color:colors.textPrimary,textAlign:'center',marginTop:spacing.sm},form:{gap:spacing.md,marginBottom:spacing.xl},input:{borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,borderRadius:radius.md,paddingHorizontal:spacing.md,paddingVertical:spacing.md,color:colors.textPrimary,...typography.body},passwordRow:{flexDirection:'row',alignItems:'center',borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,borderRadius:radius.md,paddingRight:spacing.sm},passwordInput:{flex:1,paddingHorizontal:spacing.md,paddingVertical:spacing.md,color:colors.textPrimary,...typography.body},toggle:{paddingHorizontal:spacing.sm,paddingVertical:spacing.xs},toggleText:{...typography.caption,color:colors.accent,fontWeight:'700'},forgotLink:{...typography.caption,color:colors.textSecondary,textAlign:'right'},error:{...typography.caption,color:colors.danger},actions:{gap:spacing.sm}});